config/routes.rb
Realtorest::Application.routes.draw do

  root :to => 'home#index'

  match  'page/:page'                       => 'home#index'
  
  match 'listings/search/(:page)'           => 'listings#search'
  match 'listings/download/:list_no'        => 'listings#download'
  match 'listings/:list_no/(:any)'          => 'listings#show'
  match 'listings/photo/:list_no/:photo_no' => 'listings#photo'

  match 'towns'                             => 'towns#autocomplete'

end

app/views/backbone/_initialListings.html.erb
<script>
    window.initialListings = <%= raw(@listings.to_json) %>
</script>

app/views/backbone/_search.html.erb
<script type="text/template" id="search_template">
        <form class="navbar-search pull-left" id="search-form">
        <input type="text" class="search-query autocomplete" data-provide="typeahead" data-items="10" placeholder="Search for homes in...">
        </form>
        <ul class="nav" id="nav-container">
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">More Search Options <b class="caret"></b></a>
            <ul class="dropdown-menu span4" id="advanced-search">
              <form class="form-horizontal" id="advanced-form" >
              <input type="hidden" name="mintown" value="">
              <input type="hidden" name="maxtown" value="">
              <li class="nav-header">Price</li>
              <li class="advanced-input">
                  <div class="control-group" data-control-group="price" rel="tooltip">                
                    <div class="input-prepend" >
                      <span class="add-on">$</span><input name="minprice" type="text" class="span1" placeholder="Min">
                    </div>
                    <span class="to">To</span>  
                    <div class="input-prepend">
                      <span class="add-on">$</span><input name="maxprice" type="text" class="span1" placeholder="Max">
                    </div>
                  </div>
              </li>
              <li class="nav-header">Beds &amp; Baths</li>
              <li class="advanced-input">
                  <div class="control-group" data-control-group="bedbath">
                    <label class="inline-block">
                    <select name="beds" class="span1 advanced-select">
                      <option value="1">1+</option>
                      <option value="2">2+</option>
                      <option value="3">3+</option>
                      <option value="4">4+</option>
                    </select>
                    Beds
                    </label>
                    <label class="inline-block">
                    <select name="baths" class="span1 advanced-select">
                      <option value="1">1+</option>
                      <option value="2">2+</option>
                      <option value="3">3+</option>
                      <option value="4">4+</option>
                    </select>
                    Baths
                  </label>
                  </div>
              </li>
              <li class="nav-header">Square Feet</li>
              <li class="advanced-input">
                  <div class="control-group" data-control-group="squarefeet">
                  <div class="input-append">
                    <input name="minsqft" type="text" class="span1" placeholder="Min"><span class="add-on">Sqft</span>
                  </div>
                  <span class="to">To</span>  
                  <div class="input-append">
                    <input name="maxsqft" type="text" class="span1" placeholder="Max"><span class="add-on">sqft</span>
                  </div>
                  </div>
                  <input type="submit" class="btn btn-primary" id="advanced-save" value="save">
              </li>
              </form>
            </ul>
          </li>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="sort-dropdown">Sort By: Newest <b class="caret"></b></a>
            <ul class="dropdown-menu span3" id="advanced-search">
                <li><a href="#" class="sort" data-sort="newest">Newest</a></li>
                <li><a href="#" class="sort" data-sort="priceasc">Price (Lowest to Highest)</a></li>
                <li><a href="#" class="sort" data-sort="pricedsc">Price (Highest to Lowest)</a></li>
                <li><a href="#" class="sort" data-sort="numphoto">Number of Photos</a></li>
            </ul>
          </li>
          <li class="divider-vertical"></li>
        </ul>
</script>

app/views/backbone/_tile.html.erb
<script type="text/template" id="tile_template">
    <div class="tile">
         <div class="padded">
                <a href="/listings/<%%= id %>/<%%= address_slug %>">
                <img src="/images/<%%= photo_url %>" alt="<%%= street_no_titleized %> <%%= street_name_titleized %>, <%%= town.    long %>, <%%= town.state %>" />
                </a>
                <div class="tags clearfix">
                    <span class="price badge badge-success"><%%= list_price_currency %></span>
                    <span class="address clearfix"><strong title='<%%= street_no_titleized %> <%%= street_name_titleized %>'><%%=   address_truncated %></strong></span>
                     <span class="location"><%%= town.long %>, <%%= town.state %> </span>
                </div>
         </div>
         <div class="gray-area">
             <div class="gray-section-wrapper clearfix">
                 <div class="gray-section">
                     <%%= no_bedrooms %> Beds
                 </div>
                 <div class="gray-section gray-section-middle">
                     <%%= no_full_baths + no_half_baths %> Baths
                 </div>
                 <div class="gray-section gray-section-right">
                     <%%= square_feet_delimited %> sqft
                 </div>
             </div>
         </div>
    </div> <!-- .tile -->
</script>

app/views/backbone/_tiles.html.erb
<script type="text/template" id="tiles_template">
        <div class="row-fluid" id="content">
            <div class="span12" id="tiles">
    

            </div>
        </div><!-- row-fluid -->
</script>